### ISSUE TITLE
Fix Test Cases of OCEX Pallet

### ISSUE THREAD

**Issue by Gauthamastro** [Polkadex-Substrate/Polkadex#176]
Due to the recent change in the structure of LinkedAccount, Test cases are failing, update the test cases to fix it. 

The update needs to be done to develop

**Comment by Gauthamastro** [comment]
@mambisi is this complete?

**Comment by mambisi** [comment]
`cargo test` doesn't show any errors for ocex pallet

**Comment by Gauthamastro** [comment]
Okay thanks, closing this issue for now
