### ISSUE TITLE
Generic ERC-20 token transfer

### ISSUE THREAD

**Issue by frankli-dev** [Polkadex-Substrate/Polkadex#177]
1. Update `chainbridge & example` pallet under `https://github.com/Polkadex-Substrate/chainbridge-substrate` repo.
- [x] Transfer ERC20 token from ethereum to Polkadex ChainSafe(H160) asset

Current workflow:
When deposit event happens on ethereum side, Chainbridge relayer captures it and make an extrinsic call to Polkadex. (acknowledge_proposal)

acknowledge_proposal → vote_for → commit_vote, try_resolve_proposal → finalize_execution or cancel_execution → call.dispatch (Example.transfer)

In Example.transfer, it transfers the amount of tokens using the bridge account as the source. Need to figure out how we can mint these assets as generic.

- [x] Transfer ChainSafe(H160) asset from Polkadex to ERC20 token
This is currently WIP.

2. Update runtime
Need to replace the current native Currency with the ChainSafe asset in runtime

**Comment by frankli-dev** [comment]
@mambisi I will try to improve this issue context. Meanwhile please check the current workflow of `chainbridge` and `example` pallet.

**Comment by Gauthamastro** [comment]
@frankli-dev Don't replace the native currency with Chainsafe(H160). We can use ORML token for minting to a given account for any AssetID.

**Comment by mambisi** [comment]
Ok Frank, which branch should i base on?

**Comment by frankli-dev** [comment]
> Ok Frank, which branch should i base on?

`chainbridge-temp`

**Comment by Gauthamastro** [comment]
@mambisi @frankli-dev I believe this is completed, right?
