### ISSUE TITLE
Add additional asset ids

### ISSUE THREAD

**Issue by haerdib** [Polkadex-Substrate/Polkadex#199]
The current openfinex server does not yet support polkadexs asset ids. To test the polkadex-worker flow additional asset-ids that are supported by openfinex would be great. After testing, only the market "btcusd" seemed to be active. So I'd propose to add the following asset ids:
- btc
- usd

**Comment by ksr30** [comment]
@Gauthamastro  :- Just add new asset ids to primitives and also to chain_spec for endowing balance of these new assets to alice and bob

**Comment by ksr30** [comment]
Done
