### ISSUE TITLE
Uniswap v2 Ink smart contract

### ISSUE THREAD

**Issue by frankli-dev** [Polkadex-Substrate/Polkadex#217]
**Is your feature request related to a problem? Please describe.**
Related to Polkapool

**Describe the solution you'd like**
https://github.com/Uniswap/uniswap-v2-core/tree/master/contracts
https://github.com/Uniswap/uniswap-v2-periphery/tree/master/contracts
Convert solidity smart contract into ink smart contract

**Describe alternatives you've considered**
TDD;

**Additional context**
TDD;

**Comment by visiondream3** [comment]
Expected closure : 14th July

**Comment by frankli-dev** [comment]
- Implementing LiquidityPool as a contract's storage instead of generating a new pair which leads complicated hash/salt.
- Big blocker now: Call runtime pallet's function to migrate real erc20 tokens from user's wallet to uniswap or vice versa.

**Comment by frankli-dev** [comment]
- Communicating with Santiago about the above blocker. Got basic understanding about chains_extension but not yet get the code example or the direct contact.
- Implementing add_liquidity, remove_liquidity logic to LiquidityPool

**Comment by frankli-dev** [comment]
- Add/Remove liquidity
- Swap (swap one path, multi path, swap with supply, swap with target)
- Calculate liquidity share for liquidity providers
- Other queries (get liquidity status, get supply/target)
- Chain Extension: Interact with runtime pallet to transfer tokens between user vs pool, user vs user
- Integration Test (deploy ink contract to polkadex and play around it)
- Writing Tests
- Finalize Membisi's Polkapool with uniswap_v2 ink contract
