### ISSUE TITLE
Uniswap - Integration Tests, Writing Tests, Finalize Polkapool

### ISSUE THREAD

**Issue by pavankanteti** [Polkadex-Substrate/Polkadex#223]

**Comment by frankli-dev** [comment]
Integration Test (deploy ink contract to polkadex and play around it)
Writing Tests
Finalize Membisi's Polkapool with uniswap_v2 ink contract

**Comment by pavankanteti** [comment]
EOD 30/7/21

**Comment by pavankanteti** [comment]
@Gauthamastro and @simonsso to review
