### ISSUE TITLE
Compare the features given in Notion and create issues if necessary

### ISSUE THREAD

**Issue by pavankanteti** [Polkadex-Substrate/Polkadex#236]

**Comment by frankli-dev** [comment]
https://www.notion.so/polkadex/Polkadex-IDO-Design-d926b7338eb24aa4a600462d0909cb16

**Comment by pavankanteti** [comment]
Gautham to confirm on the features

**Comment by Gauthamastro** [comment]
Where is the feature list? @pavankanteti
