### ISSUE TITLE
[IDO pallet] Several extrinsics do not update the value of storage items for tracking funds, causing inconsistency in the runtime state

### ISSUE THREAD

**Issue by pavankanteti** [Polkadex-Substrate/Polkadex#249]
Link: https://github.com/Polkadex-Substrate/audit-sr-labs/issues/9 

Summary
In the IDO pallet, the withdraw_token, withdraw_raise and participate_in_round do not update the storage items tracking the amounts of funds. This creates inconsistencies in the runtime state that could lead to financial loss for users.

Issue details
The withdraw_token does not update the value of actual_raise, enabling a creator to call this extrinsic multiple times. No matter how many times the creator calls this extrinsic, the actual_raise value for the funding round would remain unchanged. This enables the creator to transfer remaining_token amount of tokens to a beneficiary arbitrary amount of times.

Similarly, the withdraw_raise extrinsic does not check whether the raise of the funding round was already withdrawn or not. A creator can call this extrinsic over and over and transfer total_raise amount of tokens to a beneficiary arbitrary amount of times.

The extrinsic participate_in_round also suffers from a similar issue. If an investor calls it for the second time, it will deposit the funds from his account but it will replace his previous share info (saved in InvestorShareInfo). If an investor calls this extrinsic the second time, they will lose min(amount_1, amount_2) amount of tokens considering the two extrinsic calls.

Risk
These inconsistencies may lead to financial loss in tokens for users. Such bugs could also undermine the reputation and trust in the system.

Mitigation
We suggest to keep the value of these storage items updated in the respective extrinsics and and check the value before performing any balance transfer. Consider limiting the number of times (to for example, only once) these extrinsics can be called.

**Comment by mambisi** [comment]
Since how funds are collected and transferred is changed in #252, this task can move to a 1 sprint point after the #252 is merged

**Comment by pavankanteti** [comment]
Comments from SR Labs: 
- Withdraw_tokens can still be called multiple times by the creator, this should be limited to only one call.
- Furthermore, it might make sense to limit withdraw_token, and withdraw_raise to be only callable after the round is over. @mambisi @simonsso

**Comment by simonsso** [comment]
Put it in next sprint backlog.
