### ISSUE TITLE
[IDO pallet] Logic inconsistency in handling funding capital could cause IDO creators financial loss

### ISSUE THREAD

**Issue by pavankanteti** [Polkadex-Substrate/Polkadex#252]
Summary
Logic inconsistency in the IDO pallet (Polkadex/pallets/Polkadex_Ido/src/lib.rs) could cause financial loss to the IDO creators.

Issue details
The IDO pallet (Polkadex/pallets/Polkadex_Ido/src/lib.rs) allows investors to invest in a funding round using the participate_in_round extrinsic. This extrinsic moves the funds from the investors account to the module's account (Self::get_wallet_account()).

(in participate_in_round):
```

<T as Config>::Currency::transfer(AssetId::POLKADEX, &investor_address, &Self::get_wallet_account(), amount)?;
```
Later when the funding round creator demands to withdraw the funds raised, by calling the withdraw_raise the funds to be transferred are transferred from his account and not the module's account as follows

(in withdraw_raise:)
```

pub fn withdraw_raise(origin, round_id: T::Hash, beneficiary: T::AccountId) -> DispatchResult {
	let creator: T::AccountId = ensure_signed(origin)?;
[...]
	let total_raise = funding_round.amount.saturating_mul(funding_round.token_a_priceper_token_b);
	<T as Config>::Currency::transfer(AssetId::POLKADEX, &creator, &beneficiary, total_raise)?;
	Self::deposit_event(RawEvent::WithdrawRaised(round_id, creator));
[...]
}

```
Risk
The inconsistency between different accounts used for fundraising in the funding rounds could cause financial loss for the IDO creators, which will defeat the purpose of this pallet.

Mitigation
We suggest using appropriate accounts in this pallet for the accumulation of the raised funds and transfering them to the right beneficiary.

**Comment by pavankanteti** [comment]
EOD 29/7/21

**Comment by simonsso** [comment]
@pavankanteti  could we have link to the original issue here so I do not have to spend 15 minutes searching for it https://github.com/Polkadex-Substrate/audit-sr-labs/issues/12

**Comment by pavankanteti** [comment]
@simonsso Noted
