### ISSUE TITLE
(IDO Pallet) Vote Team Project

### ISSUE THREAD

**Issue by pavankanteti** [Polkadex-Substrate/Polkadex#257]
Add a Dispatcheable function start_vote_team_project(origin : AccountID, duration : T::BlockNumber)
This function start votes for team project funding round and ends at current block number + duration block, investors will have the oppurtunity to vote during the voting period.
Offchain worker will add the team projects to AvailableTokenSale storage when votes reach 50% + 1 of majority whitelisted investors
AvailableTokenSale team => team

**Comment by pavankanteti** [comment]
Add a Dispatcheable function vote_for_team_project(origin : AccountID, team: AccountID)
Add vote from the origin (invester) for a  specific team project, "add the Team project to AvailableTokenSale when majority is reached"
So thing missing i am still looking through it, it is initial draft of things missing in the IDO Pallet

**Comment by mambisi** [comment]
Voting period show end before investors can start participating
