### ISSUE TITLE
[Polkapool pallet] The current implementation of claim_feeless_transaction allows attackers to DoS the feeless transaction queue

### ISSUE THREAD

**Issue by pavankanteti** [Polkadex-Substrate/Polkadex#259]
Summary
In the polkapool pallet (Polkadex/pallets/polkapool/src/lib.rs), malicious users are able to leverage a DoS attack on the feeless transaction queue by issuing calls via claim_feeless_transaction with a sufficiently large weight.

Issue details
In the polkapool pallet in the claim_feeless_transaction extrinsic a maximum total weight (MaxAllowedWeight) is configured for all feeless transactions for a given block. The current runtime configuration for MaxAllowedWeight is currently 20% of the maximum block weight.

    pub MaxAllowedWeight: Weight = Perbill::from_percent(20) *
        RuntimeBlockWeights::get().max_block;
Since this is a relatively small value, a malicious user could issue calls with this extrinsic for each block with a sufficiently heavy weight to prevent other users from successfully submitting feeless transactions for a given block, since then the next user submitting a call for the same block will receive the NoMoreFeelessTxnsForThisBlock error as shown below.

        pub fn claim_feeless_transaction(origin, stake_price: <T as Config>::Balance, call: Box<<T as Config>::Call>) -> dispatch::DispatchResult {
[...]
            let call_weight =  call.get_dispatch_info().weight;

            let mut stored_exts: ExtStore<<T as Config>::Call, <T as Config>::PalletsOrigin> = Self::get_next_block_txns();
            stored_exts.total_weight = stored_exts.total_weight.saturating_add(call_weight);
            ensure!(stored_exts.total_weight <= T::MaxAllowedWeight::get(), Error::<T>::NoMoreFeelessTxnsForThisBlock);
[...]
Risk
Malicious users could leverage this to delay or censor other user's transactions. Unsuccessful attempts with claim_feeless_transaction on a certain block will also cause users a financial loss in the transaction fee for this extrinsic. In addition, malicious collators could arbitrarily rearrange the order of the incoming claim_feeless_transaction calls, in order to censor certain transactions scheduled for a block.

Mitigation suggestion
We suggest executing the extrinsic with its normal fee rather than the reduced fee of claim_feeless_transaction even if the stored_exts.total_weight has reached MaxAllowedWeight (without the guarantee of executing it in the given block). This could be done by executing the call via the dispatch method and then charging max(Fee(claim_feeless_transaction), Fee(call)). This should mitigate against censorship attacks while ensuring that all necessary fees are paid.

**Comment by Gauthamastro** [comment]
Will be solved later this week, after discussing with SBP

**Comment by Gauthamastro** [comment]
This is not yet solved
