### ISSUE TITLE
Insufficient extrinsics weights

### ISSUE THREAD

**Issue by pavankanteti** [Polkadex-Substrate/Polkadex#270]
Link: https://github.com/Polkadex-Substrate/audit-sr-labs/issues/19

# Summary

Throughout Polkadex and it's dependencies (Chainbridge, ORML, Polkadot-ethereum, SubstraTEE-registry), a subset of extrinsics have insufficient assigned weights. This potentially allows attackers to cause block timeouts by calling insufficiently weighted extrinsics that would take longer to execute than what their assigned weight indicated. We suggest to use a best practice benchmarking approach when assigning weights to extrinsics.

# Issue details

Several pallets among the Polkadex repositories contain extrinsics that have a default (e.g. 0, `10000`, etc.) weight assigned. The following extrinsics from the in-scope pallets in Polkadex and its dependencies are affected:

| Repository |  Pallet |  Extrinsic | Weight |
| - | - | - | - |
| open-runtime-module-library | benchmarking | set_value | 0 |
| open-runtime-module-library | benchmarking | dummy | 0 |
| chainbridge-substrate | chainbridge | set_threshold | 195000000 |
| chainbridge-substrate | chainbridge | set_resource | 195000000 |
| chainbridge-substrate | chainbridge | remove_resource | 195000000 |
| chainbridge-substrate | chainbridge | whitelist_chain | 195000000 |
| chainbridge-substrate | chainbridge | add_relayer | 195000000 |
| chainbridge-substrate | chainbridge | remove_relayer | 195000000 |
| chainbridge-substrate | chainbridge | reject_proposal | 195000000 |
| chainbridge-substrate | example-erc721 | mint | 195000000 |
| chainbridge-substrate | example-erc721 | transfer | 195000000 |
| chainbridge-substrate | example-erc721 | burn | 195000000 |
| chainbridge-substrate | example-pallet | transfer_hash | 195000000 |
| chainbridge-substrate | example-pallet | transfer_native | 195000000 |
| chainbridge-substrate | example-pallet | transfer_erc721 | 195000000 |
| chainbridge-substrate | example-pallet | transfer | 195000000 |
| chainbridge-substrate | example-pallet | remark | 195000000 |
| chainbridge-substrate | example-pallet | mint_erc721 | 195000000 |
| Polkadex | Polkadex_Ido | attest_investor | 10000 |
| Polkadex | Polkadex_Ido | participate_in_round | 10000 |
| Polkadex | Polkadex_Ido | withdraw_raise | 10000 |
| Polkadex | Polkadex_Ido | withdraw_token | 10000 |
| Polkadex | polkapool | unstake | 10000 |
| Polkadex | polkapool | slash_stake | 10000 |
| Polkadex | pdex-migration | mint | 10000 |
| Polkadex | fungible-assets | create_token | 10000 |
| Polkadex | fungible-assets | set_vesting_info | 10000 |
| Polkadex | fungible-assets | claim_vesting | 10000 |
| Polkadex | fungible-assets | set_metadata_fungible | 10000 |
| Polkadex | fungible-assets | mint_fungible | 10000 |
| Polkadex | fungible-assets | burn_fungible | 10000 |
| Polkadex | fungible-assets | attest_token | 10000 |
| Polkadex | fungible-assets | modify_token_deposit_amount | 10000 |
| Polkadex | ocex | deposit | 10000 |
| Polkadex | ocex | release | 10000 |
| Polkadex | ocex | withdraw | 10000 |
| Polkadex | ocex | register | 10000 |
| Polkadex | ocex | add_proxy | 10000 |
| Polkadex | ocex | remove_proxy | 10000 |
| polkadot-ethereum | transfer | transfer_upwards | 10 |
| polkadot-ethereum | transfer | transfer | 10 |

# Risk

Underweighted extrinsics allow attackers to cause block timeouts by calling these insuffienctly weighted extrinsics that would take longer to execute than what their assigned weight indicates. In the case of parachains, having blocks that execute longer than required and as a result exceeding a block production time of six seconds could stall the block inclusion to the relay chain.

Note: not all the affected extrinsics are callable by any user, as some of them require a root origin. Still, underweighted root calls could accidentally cause the block production exceed the 6 seconds limit.

# Mitigation

We recommend to use the benchmarking approach [1] that is used in Substrate and Polkadot for assigning weights to extrinsics.

[1] https://github.com/paritytech/substrate/tree/master/frame/benchmarking

**Comment by simonsso** [comment]
The benchmarking build can be run in a few hours to generate balanced weights for all extrinsics.

Easiest approach is to define one fixed computer to always run it on to get a baseline

1 create a build script which runs the benchmarking build
2 is benchmark macro missing from where it should have been?
