### ISSUE TITLE
Scripts for testing ido_pallet

### ISSUE THREAD

**Issue by simonsso** [Polkadex-Substrate/Polkadex#278]
Extricics and RPC calls can be issued from scripts/cli tools (python subratate-api typescript ) etc etc

Such a script could call functionality of a running chain and verify its results.

For IDO pallet, on the block chain level: create a script with a number of operations to start and complete a funding round with several investors and all steps needed for a full round.

Investigate at least 
* successful round
* failed rounds
* random knock out
* rejected offers

The scripts shall be able to run on staging chain

**Comment by pavankanteti** [comment]
Already implemented
