### ISSUE TITLE
Modify Register Dispatchable function in OCEX Pallet

### ISSUE THREAD

**Issue by zktony** [Polkadex-Substrate/Polkadex#292]
**Is your feature request related to a problem? Please describe.**
Right now, User has to call [register dispatchable function](https://github.com/Polkadex-Substrate/Polkadex/blob/develop/pallets/ocex/src/lib.rs#L174-L182) to register on blockchian which is not User friendly at all.

**Describe the solution you'd like**
Modify Register function so that it can only be called by Enclave, just like [this](https://github.com/Polkadex-Substrate/Polkadex/blob/develop/pallets/ocex/src/lib.rs#L145-L146). 

**Additional context**
Rest Sign Up process will be in Enclave itself.

**Comment by simonsso** [comment]
Could we not solve this by issuing several calls from the APP to the API?
