### ISSUE TITLE
Fix broken builds on Develop Branch

### ISSUE THREAD

**Issue by pavankanteti** [Polkadex-Substrate/Polkadex#308]
The develop branch of TEE-worker is broken because it is dependent on Polkadex's develop branch. @frankli-dev  been trying to fix but having another compiling issue on running TEE-worker. 

- Fix Develop branch
- Fix Internal testnet

**Comment by simonsso** [comment]
@frankli-dev  and @pavankanteti could you please elaborate some more on the tasks and presuppose of this ticket

**Comment by frankli-dev** [comment]
sure. The develop branch of TEE-worker is broken because it is dependent on Polkadex's `develop` branch. I've been trying to fix but having another compiling issue on running TEE-worker. I need some help from Gabriel or ZK.
