### ISSUE TITLE
Uniswap Ink contract should allow any assets

### ISSUE THREAD

**Issue by pavankanteti** [Polkadex-Substrate/Polkadex#315]

**Comment by frankli-dev** [comment]
Right now, Uniswap ink contract only allows Ethereum addresses. We need to extend it to AssetId including Polkadex, BTC, USD, etc
Modification is also needed on chain extension on runtime.

**Comment by frankli-dev** [comment]
https://github.com/paritytech/ink/issues/1001

**Comment by frankli-dev** [comment]
https://github.com/paritytech/ink/issues/1011

**Comment by pavankanteti** [comment]
Outdated. New issues will be created for this pallet later.
