### ISSUE TITLE
Migrate to Aug substrate tag

### ISSUE THREAD

**Issue by pavankanteti** [Polkadex-Substrate/Polkadex#331]
**Repositories to be Migrated**

- [ ] [Polkadex Node](https://github.com/Polkadex-Substrate/Polkadex)

- [ ] [Polkadex Primitives](https://github.com/Polkadex-Substrate/polkadex-primitives)

- [ ] [ORML Pallets](https://github.com/Polkadex-Substrate/open-runtime-module-library)

**Comment by haerdib** [comment]
I guess this one is outdated - it should be september + 1 tag, is that correct?
