### ISSUE TITLE
Update to substrate september tag + 1

### ISSUE THREAD

**Issue by haerdib** [Polkadex-Substrate/Polkadex#371]
The following libraries should be updated on the node side to the substrate september tag:

- [x] OCEX pallet (https://github.com/Polkadex-Substrate/Polkadex/issues/366)
- [x] [pallet substratee registry ](https://github.com/Polkadex-Substrate/pallet-substratee-registry), there is a branch already created here: https://github.com/Polkadex-Substrate/pallet-substratee-registry/tree/substrate-monthly-2021-09%2B1
- [x] [Polkadex primitives](https://github.com/Polkadex-Substrate/polkadex-primitives), possible branch: https://github.com/Polkadex-Substrate/polkadex-primitives/tree/substrate-monthly-2021-09+1
- [x] ORML pallets: https://github.com/Polkadex-Substrate/open-runtime-module-library
- [x] The node itself: https://github.com/Polkadex-Substrate/Polkadex/tree/develop

As discussed in https://github.com/Polkadex-Substrate/sgx-runtime/pull/4 `branch="master"` should be specified in the .toml and the commit https://github.com/paritytech/substrate/commit/dd297887c653e344c566e976c050b01f7dea8eef) used (tag commit [20a9bbb1fe47fcd62fcd64b2fa32456b4f434aaf](https://github.com/paritytech/substrate/commit/20a9bbb1fe47fcd62fcd64b2fa32456b4f434aaf) causes problems for GA, but both commits are the same).

It would be great if you could tick mark the specific libraries that have been updated. :)

**Comment by haerdib** [comment]
Linking related (but outdated?) issue: https://github.com/Polkadex-Substrate/Polkadex/issues/331

**Comment by mambisi** [comment]
Resolved in https://github.com/Polkadex-Substrate/polkadexTEE-worker/tree/mz-substrate-master

**Comment by mambisi** [comment]
commit : 88c64e06471cc12aa9b25290f24d5566bcb5dd82

**Comment by haerdib** [comment]
It's almost working. Almost, because I'm encountering the following problem on the worker side:
I'm importing `node-polkadex-runtime`, which depends on the orml pallet [orml-vesting](https://github.com/Polkadex-Substrate/Polkadex/blob/main/runtime/Cargo.toml#L87). While this is patched on the node side to the branch of Gautham (https://github.com/Polkadex-Substrate/Polkadex/blob/main/Cargo.toml#L13), I can not do the same on the worker side, because I'm not importing this pallet directly.
Final story short: Due to this pallet the worker .lock file ends up with two different sp-std imports, rending a cargo update -precise impossible.

Could you point the pallet to the correct branch direclty?

**Comment by haerdib** [comment]
Ah well, I was able to patch it anyway - not sure if that's the best solution though, but it's working :)

**Comment by haerdib** [comment]
Was fixed with https://github.com/Polkadex-Substrate/Polkadex/pull/376
