### ISSUE TITLE
Build Failiure

### ISSUE THREAD

**Issue by munnatamton** [Polkadex-Substrate/Polkadex#393]
I've cloned latest version of polkadex. `cargo build --release` causing error.

These are the runtime error Im getting

![Screenshot from 2021-11-15 22-52-31](https://user-images.githubusercontent.com/51350211/141826307-5b79c48f-5e62-46cf-aa60-c9335ac18095.png)

![Screenshot from 2021-11-15 22-52-56](https://user-images.githubusercontent.com/51350211/141826311-6fbc9e8e-6b40-4c01-a715-b845af041937.png)

`rustup show` looks like this.

![Screenshot from 2021-11-15 22-53-20](https://user-images.githubusercontent.com/51350211/141826322-6aee9122-9eef-4502-9ab6-6b9fa14823b7.png)

Is there any solution to this?/

**Comment by ilja-khabarov** [comment]
@munnatamton try running **install_rust.sh** in project root

**Comment by munnatamton** [comment]
> @munnatamton try running **install_rust.sh** in project root

@ilja-khabarov  done but Error still exist

**Comment by munnatamton** [comment]
Fixed it by running `rustup target add wasm32-unknown-unknown` in **project root**.
