### ISSUE TITLE
Membership: Burn 100 PDEX vs lock TBD tokens for TBD days. 

### ISSUE THREAD

**Issue by pavankanteti** [Polkadex-Substrate/Polkadex#401]
configured by governance

**Comment by pavankanteti** [comment]
Already implemented

**Comment by jangorecki** [comment]
It would be quite useful for dev community if issues closed like this, having already implemented status, will have a link to PR(s) / commit(s) that were actually implementing required functionality. So the community can audit code more easily and spot any potential bugs.
Fyi @Gauthamastro
