### ISSUE TITLE
Docker image build failed

### ISSUE THREAD

**Issue by wi1dcard** [Polkadex-Substrate/Polkadex#408]
**Describe the bug**
Failed to build the docker image. Output:

```
#0 76.84 error: failed to load manifest for workspace member `/Polkadex/node`
#0 76.84
#0 76.84 Caused by:
#0 76.84   failed to parse manifest at `/Polkadex/node/Cargo.toml`
#0 76.84
#0 76.84 Caused by:
#0 76.84   feature `edition2021` is required
#0 76.84
#0 76.84   consider adding `cargo-features = ["edition2021"]` to the manifest
```

**To Reproduce**
Clone the repo and checkout `v1.0.8`, run the following command:

```
docker build -t polkadex-node:v1.0.8 .
```

**Expected behavior**
Build the image successfully.

**Screenshots**
No

**Additional context**
No

cc @freehere107, @MittWillson

**Comment by felixfaisal** [comment]
Hey @wi1dcard, So we do have a working image on Dockerhub, you can pull it using the below command while we resolve this 
```bash
docker pull polkadex/mainnet:v1.0.8
```
