### ISSUE TITLE
Install Governance Pallets

### ISSUE THREAD

**Issue by Gauthamastro** [Polkadex-Substrate/Polkadex#41]
**Describe the solution you'd like**
Install Council and Treasury pallets from FRAME.

**Additional context**
Refer to Slack and Whitepaper for more details

**Comment by ayushmishra2005** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DEX-302 Integrate Identity Pallet + Governance configuration](https://trello.com/c/6pjS7pyC/8-dex-302-integrate-identity-pallet-governance-configuration)
