### ISSUE TITLE
Implement testnet/mainet as features in cargo 

### ISSUE THREAD

**Issue by Gauthamastro** [Polkadex-Substrate/Polkadex#42]
**Is your feature request related to a problem? Please describe.**
The current configuration compiles the whole repo, which is unnecessary in most cases. We need to have a selection flag while compiling to compile the required ones selectively.

**Describe the solution you'd like**
If it is possible to make the testnet and mainnet as features, then we use  ``` cargo build --features=mainnet``` for compiling packages only related to mainnet and similarly for testnet

**Describe alternatives you've considered**
Let me know other alternatives in the comments

CC: @ayushmishra2005 @ksr30

**Comment by ayushmishra2005** [comment]
Commands to execute mainnet and testnet as features are:

`cargo build --manifest-path bin/polkadex/Cargo.toml --features mainnet`

`cargo build --manifest-path bin/polkadex/Cargo.toml --features testnet`

cc @Gauthamastro @ksr30
