### ISSUE TITLE
Improve CI/CD 

### ISSUE THREAD

**Issue by felixfaisal** [Polkadex-Substrate/Polkadex#428]
So currently, the CI/CD needs to be improved and have updated the branch names, 

It should also include the following: 
- [x] Check for rustfmt format
- [x] Check for any warnings 
- [x] Check for any clippy warnings 
- [x] Check for any unused dependencies 
- [x] Check for code coverage and pass only if certain threshold is met.

**Comment by serhii-temchenko** [comment]
> Check for code coverage and pass only if certain threshold is met.

What threshold is acceptable?
