### ISSUE TITLE
Extend Github Actions to run cargo test for each pallets

### ISSUE THREAD

**Issue by Gauthamastro** [Polkadex-Substrate/Polkadex#44]
**Is your feature request related to a problem? Please describe.**
The Github actions are building the whole project as one and testing it. Instead, it would be better to have cargo test workflows for each pallet.

**Describe the solution you'd like**
Different cargo test workflows for each pallet, mainnet, and testnet separately

**Comment by ksr30** [comment]
job for mainnet and testnet is pending. (Dependent on Issue #42)

**Comment by Gauthamastro** [comment]
#42 is closed. 
 
   CC @ksr30

**Comment by ksr30** [comment]
#72 will solve it
