### ISSUE TITLE
Certificate Validity Governance Managed Value

### ISSUE THREAD

**Issue by pavankanteti** [Polkadex-Substrate/Polkadex#532]
https://github.com/Polkadex-Substrate/pallets/blob/polkadot-v0.9.28/teerex/ias-verify/src/lib.rs#L212
this value must be available for governance update

**Comment by zktony** [comment]
These pallets are not in our runtime. How can I add governance update for this?

**Comment by 35359595** [comment]
First - [this](https://github.com/Polkadex-Substrate/pallets/pull/4)
Next - [this](https://github.com/Polkadex-Substrate/Polkadex/commit/724be891f1f6c4f7b452f1d529df34944faa4ad3)
Now make [this](https://github.com/Polkadex-Substrate/Polkadex/blob/724be891f1f6c4f7b452f1d529df34944faa4ad3/runtime/src/lib.rs#L1263-L1264) governable and after first PR merged change branch name back [here](https://github.com/Polkadex-Substrate/Polkadex/blob/724be891f1f6c4f7b452f1d529df34944faa4ad3/pallets/ocex/Cargo.toml#L25).
