### ISSUE TITLE
`convert_asset_id` to look for clashes 

### ISSUE THREAD

**Issue by felixfaisal** [Polkadex-Substrate/Polkadex#534]
In the current implementation of this function, There can be clashes with other assets in `asset handler` pallet which can lead to malicious activity.

**Comment by nuel77** [comment]
Problem:
convert_asset_id  maps from u256 to u128,  so there can be clashes between two assets. Consider asset A with maps to a' and is present in the pallet. A malicious attacker can find a another asset B which also maps to a' and use B to mint A in our systems.

Proposed Solution:
when minting assets a' check if the original resource id already registered.
