### ISSUE TITLE
changes required in deposit pallet

### ISSUE THREAD

**Issue by nakul1010** [Polkadex-Substrate/Polkadex#543]
- [x] Check if account register
- [x] change name of get_custodian_account as it is misleading
- [x] move [transfer asset](https://github.com/Polkadex-Substrate/Polkadex/blob/f299d744deabb7830d97347d0ad8e48387661242/pallets/ocex/src/lib.rs#L572) above to check if asset register
- [x] Brain strom  a strategy to check if custodian account has pdex [here](https://github.com/Polkadex-Substrate/Polkadex/blob/f299d744deabb7830d97347d0ad8e48387661242/pallets/ocex/src/lib.rs#L572)

**Comment by nuel77** [comment]
> * transfer asset

strategy for custodian account balance: 
its just a one time things, so add some balance manually.
