### ISSUE TITLE
Create docker release 

### ISSUE THREAD

**Issue by felixfaisal** [Polkadex-Substrate/Polkadex#567]
We need to create a new docker image release for the latest upgrade

**Comment by serhii-temchenko** [comment]
Docker image was build and published on the docker hub ([link](https://hub.docker.com/layers/polkadex/mainnet/v4.0.0/images/sha256-e542ab44bf55bd049f0add613d98a73c5081d23f86082cfdbc688ad72af7a8b2?context=explore)). Tested (node runs properly).
