### ISSUE TITLE
Query Polkadot Accounts Who Contributed to Polkadex Crowdloan

### ISSUE THREAD

**Issue by nakul1010** [Polkadex-Substrate/Polkadex#601]
Todos to complete the issue. 
- [x] Query all the accounts, map them to the dot contributed and put them in the CSV file.
- [x] If a single account has contributed multiple times store it in increment the value.
- [x] The unit balance of Polkadot(10^10) and polkadex(10^18) is different convert it.
- [x] Hard Core the contributors in the rewards pallet storage.

**Comment by nuel77** [comment]
https://github.com/Polkadex-Substrate/crowload-data-fetcher - script to fetch contributors and save to csv

**Comment by nakul1010** [comment]
Fixed it in [reward calculatiom](https://github.com/Polkadex-Substrate/Reward-Calculation) repo
