### ISSUE TITLE
Pallet Account for Liquidity

### ISSUE THREAD

**Issue by pavankanteti** [Polkadex-Substrate/Polkadex#623]
A pallet account controlled by governance to provide liquidity provisioning to Orderbook.

**Comment by nakul1010** [comment]
All the functionality accessible to a normal account should be accessible to the liquidity pallet account. 
Make the code generic between the liquidity pallet and the ocex pallet.


### Flow Diagram

![Liquidity Pallet](https://user-images.githubusercontent.com/58786560/214238579-dc591837-6af0-4734-a794-a21cda08cc44.png)

### Extrinsic

`register_account`
The extrinsic will register a governance control account in the ocex pallet. 
Parameters, 
```
origin: governance account
u32: 32-bit unsigned integer will be used to create the main account and proxy account for the ocex pallet. 
```


`deposit_to_orderbook`
The extrinsic will deposit funds to the orderbook. 
Parameters, 
```
origin: governance account
u32: 32-bit unsigned integer that was used during registration
asset: the asset to be deposited
amount: the amount that needs to be deposited
```


`withdraw_from_orderbook`
The extrinsic will deposit funds to the orderbook. 
Parameters, 
```
origin: governance account
u32: 32-bit unsigned integer that was used during registration
asset: the asset to withdraw
amount: the amount that needs to be withdrawn  
```

The importance of having a u32 value is that multiple accounts can be registereded and controlled by governance. 


ToDos to complete the issue 
- [x] Initialize the new pallet 
- [x] Make deposit code generic in ocex pallet  
- [x] New deposit and withdrawal extrinsic in liquidity pallet. 
- [x] Set up mock environment and Test Case for liquidity pallet
