### ISSUE TITLE
Frontend Requirements for Thea Integration 

### ISSUE THREAD

**Issue by felixfaisal** [Polkadex-Substrate/Polkadex#644]
This Issue will contain list of changes required by Frontend for Thea Integration 
- [x] #645
- [x] #647
- [x] assets information. Need some config file where we keep track of supported thea assets { tokenName, assetId, decimals, networkOfOrigin }

**Comment by nuel77** [comment]
- add from account in the withdrawl storage
- assets information. Need some config file where we keep track of supported thea assets { tokenName, assetId, decimals, networkOfOrigin }
- add txhash In deposit events
