### ISSUE TITLE
Untested possible bug with reward pallet

### ISSUE THREAD

**Issue by mt-gareth** [Polkadex-Substrate/Polkadex#660]
**Describe the bug**
In the rewards pallet on the claim function there is a check to make sure that the amount about to be claimed is not over the total claimable as a sanity check. The check looks like:
```
//ensure total_rewards_claimable - rewards_claimed >= rewards_claimable
//sanity check
ensure!(
   user_reward_info
      .total_reward_amount
      .saturated_into::<u128>()
      .saturating_sub(
         user_reward_info.claim_amount.saturated_into::<u128>()
      ) >= rewards_claimable,
   Error::<T>::AllRewardsAlreadyClaimed
);
```
My question is should this check not be just ` > rewards_claimable` as they would be equal on the final claim?

**Expected behavior**
When you make the final claim, say the total_reward_amount is 1000 PDEX and claim_amount is at 500 PDEX because you already claimed half, and your rewards_claimable is now 500 PDEX, I would expect to be able to get the 500 PDEX but it looks like that would throw AllRewardsAlreadyClaimed error.

If I am misunderstanding something please disregard.

**Comment by nakul1010** [comment]
Hey @mt-gareth the example u mentioned would work as follows

alice `total_reward_amount` = 1000 PDEX
uptil now alice `claim_amount` = 500 pdex

Alice makes a final claim 
`total_reward_amount` -  `claim_amount` = 1000 - 500 = 500 pdex
500 pdex >= 500 pdex hence sanity check will pass
Release alice 500 pdex
Increment `claim_amount` = `claim_amount` + `released_amount` = 500 + 500 pdex = 1000 Pdex (ie fully claimed)

Another example for clarification  

alice `total_reward_amount` = 1000 PDEX
uptill now alice `claim_amount` = 300 pdex

Alice makes a final claim 
`total_reward_amount` -  `claim_amount` = 1000 - 300 = 700 pdex
700 pdex >= 700 pdex hence sanity check will pass
Release Alice her 700 pdex
Increment `claim_amount` = `claim_amount` + `released_amount` = 300 + 700 pdex = 1000 Pdex (ie fully claimed)

The `claim_amount` will get updated after the sanity check and not before that. 
I hope this helps!

**Comment by mt-gareth** [comment]
I see my my mistake, thank you for taking the time to explain.
