### ISSUE TITLE
Benchmarking for OCEX Pallet 

### ISSUE THREAD

**Issue by nakul1010** [Polkadex-Substrate/Polkadex#683]
The benchmarking for the ocex pallet is failing due to changes done for orderbook v2. To address this issue, there are a couple of 

ToDos that need to be completed:
- [ ]  Fix the existing benchmark code.
- [ ] Extrinsics created & changed for the orderbook should have benchmarks.

**Comment by serhii-temchenko** [comment]
Plus CI workflow changes like [this](https://github.com/Polkadex-Substrate/Polkadex/pull/681/commits/2d30474730703ca059e650481ce8b99fff97bb0f) to pass CI should be reverted.
