### ISSUE TITLE
Typo in theaStaking.stakingLimits() extrinsic

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex#703]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fsolochain.polkadex.trade#/chainstate

![image](https://user-images.githubusercontent.com/6218678/230786323-c5ed28cb-2736-4584-8349-b556c291b2c9.png)

**Comment by Gauthamastro** [comment]
Not applicable anymore
