### ISSUE TITLE
CI/CD Integration

### ISSUE THREAD

**Issue by jaxter03** [Polkadex-Substrate/Polkadex#71]
**Proposed Architecture**

![Untitled Diagram](https://user-images.githubusercontent.com/40355376/104123853-75585600-5373-11eb-976d-37c7b94ae99c.jpg)

**Workflows Checklist**

**Workflow 1**
- [x] Install Dependencies.
- [ ] Check Code Formatting.
- [x] Run Automated Tests.
- [x] Upload Code coverage as an Artifact.
- [x] Cache Dependencies.

**Workflow 2**
- [x]  Install Dependencies.
- [ ] Check Code Formatting.
- [x] Run Automated Tests.
- [x] Build Project.
- [x] Upload Build as Artifact.
- [x] Cache Dependency.

**Workflow 3**
- [x] Install Dependencies.
- [ ] Check Code Formatting.
- [x] Run Automated Tests.
- [x] Upload Code coverage as an Artifact.
- [x] Cache Dependencies.
- [ ] Check Copyright & License

**Workflow 4**
- [x]  Install Dependencies.
- [ ] Check Code Formatting.
- [x] Run Automated Tests.
- [x] Upload Code coverage as an Artifact.
- [x] Build Project.
- [x] Upload Build as an Artifact.
- [x] Create a Release.
- [x] Upload Coverage to Codecov.

**Comment by Gauthamastro** [comment]
@ksr30  is this complete?

**Comment by ksr30** [comment]
No @Gauthamastro .... Code formatting and Copyright & License check are left.
