### ISSUE TITLE
Add Cargo commands in Github pipeline

### ISSUE THREAD

**Issue by ayushmishra2005** [Polkadex-Substrate/Polkadex#73]
**Is your feature request related to a problem? Please describe.**
As a part of #42 , we enabled Cargo to build `testnet/mainnet` as features. We should add same commands in github pipeline to make sure both features are compiling succsessfully

**Describe the solution you'd like**
Add below commands in github pipeline:

`cargo build --manifest-path bin/polkadex/Cargo.toml --features mainnet`

`cargo build --manifest-path bin/polkadex/Cargo.toml --features testnet`

**Comment by ksr30** [comment]
yes @ayushmishra2005, I was going to do  that (https://github.com/Polkadex-Substrate/Polkadex/issues/44)

**Comment by ksr30** [comment]
#72 will solve it
