### ISSUE TITLE
Parachain Assets Decoding failure.

### ISSUE THREAD

**Issue by Gauthamastro** [Polkadex-Substrate/Polkadex#737]
<img width="863" alt="image" src="https://user-images.githubusercontent.com/17110878/235416829-e061bf8c-cc5e-4947-9963-c708d001ddff.png">

It happened during mock deposit from parachain to solochain via thea. Thea successfully transported the data

<img width="1372" alt="image" src="https://user-images.githubusercontent.com/17110878/235416953-62e5db32-d1f5-4ef9-850a-1a8c1304981e.png">

**Comment by Gauthamastro** [comment]
Closed by https://github.com/Polkadex-Substrate/parachain/pull/41

**Comment by pavankanteti** [comment]
https://github.com/Polkadex-Substrate/parachain/pull/35
