### ISSUE TITLE
Build fixes

### ISSUE THREAD

**Issue by serhii-temchenko** [Polkadex-Substrate/Polkadex#744]
As a result of merges and direct commits pushes to the `Develop` branch (e.g. PR #741 and commits [35b9d04](https://github.com/Polkadex-Substrate/Polkadex/commit/35b9d04f67bc0f5876fbd67b5940cea62698d92e) and [6239ee4](https://github.com/Polkadex-Substrate/Polkadex/commit/6239ee4c2045ef3d07b796f56b63e13f065a1241)) we get broken `Develop` branch state with a list of errors in the process of building with `runtime-benchmarks` feature and default build (e.g. `cargo build`), many tests are broken as well now.

To reproduce run locally:
1) Benchmarks build - `cargo build --features runtime-benchmarks`
2) Default build - `cargo build`
3) Tests - `cargo test`

To resolve these errors should be:
- [ ] - Updated benchmarks to respect the new merged changes which were merged with PR's/commits referred in the description above.
- [ ] - Updated/fixed tests to respect the new merged changes which were merged with PR's/commits referred in the description above.

**Comment by Gauthamastro** [comment]
This is fixed by #750
