### ISSUE TITLE
Benchmarking Pallets

### ISSUE THREAD

**Issue by Gauthamastro** [Polkadex-Substrate/Polkadex#80]
**Describe the solution you'd like**
Benchmark the pallet and find out the optimum weight params for each dispatchable functions

- [ ] Custom Assets Pallet
- [ ] Identity Pallet
- [ ] Polkadex Engine
- [ ] Swap Engine

**Additional context**
[Substrate Seminar on Benchmarking](https://www.crowdcast.io/e/substrate-seminar/19)
[Shawn's Benchmarking Documentation (might be outdated)](https://www.shawntabrizi.com/substrate-graph-benchmarks/docs/#/)

Some other useful links

1. https://www.youtube.com/watch?v=Qa6sTyUqgek
2. https://www.youtube.com/watch?v=i3zW4wGexAc
3. https://github.com/paritytech/substrate/issues/6168

**Comment by ayushmishra2005** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DEX-403 Benchmark Pallets](https://trello.com/c/OCOjV7Sc/10-dex-403-benchmark-pallets)
