### ISSUE TITLE
Pass CLI flags to off chain worker

### ISSUE THREAD

**Issue by Gauthamastro** [Polkadex-Substrate/Polkadex#859]
If I understood this logic correctly - if request to localhost is unsuccessful because of multiple possible reasons (unable to serialize body length on 308 line or on request 317 line or extract/decode response etc present in `create_and_send_request` method) we are  doing aka backup request to `MAINNET_URL`? It looks like attempt to guess endpoint (e.g. if locallhost is unavailable than try `MAINNET_URL`), to be able figure out environment dynamically (basically to be ready for any environment) but because of multiple errors which could happen in `create_and_send_request` method, or whatever reason because of which loclhost is unavailable - it could bring unpredictable behavior (e.g. accessing mainnet data from dev/testing environment when for some reason "http://localhost:9944" address is unavailable). 
Does it make sense?

IMO url should be passed by CLI args, basically configured at the beginning of app run.

_Originally posted by @serhii-temchenko in https://github.com/Polkadex-Substrate/Polkadex/pull/858#discussion_r1283621685_

**Comment by serhii-temchenko** [comment]
Please consider that this logic was moved to `pallets/thea/src/resolver.rs` in PR #863 .

**Comment by Gauthamastro** [comment]
Thea doesn't use hardcoded links anymore, so this issue is not applicable anymore
