### ISSUE TITLE
Remove Generic Asset and Old engine pallet

### ISSUE THREAD

**Issue by Gauthamastro** [Polkadex-Substrate/Polkadex#86]
**Is your feature request related to a problem? Please describe.**
As we have completely removed Generic Assets and the Old Polkadex engine in these PRs https://github.com/Polkadex-Substrate/Polkadex/pull/77 and https://github.com/Polkadex-Substrate/Polkadex/pull/72. We can remove the pallets generic asset and polkadex from the pallets folder

**Comment by dnaicker** [comment]
![image](https://user-images.githubusercontent.com/7840952/108697446-8c11d100-750b-11eb-90f1-f11002ee524d.png)

Will it be possible to update the documentation on: https://github.com/Polkadex-Substrate/Documentation/blob/master/Tutorials/README1.md#create-an-asset that utilises genericAsset?

**Comment by rozgo** [comment]
GenericAsset is still reference in polkadex-frontend. https://github.com/Polkadex-Substrate/polkadex-frontend/blob/main/src/components/general/MarketOrderAction/index.tsx#L36

Probably needs to be updated as well.

**Comment by dnaicker** [comment]
Is there a way to continue the tutorial using the new available options that don't contain genericAsset? In the tutorial it is used for creating a custom token. The new values provided range from: system, balance....and a few more, maybe audit. I tried using different ones but am unsure how to continue.

**Comment by Gauthamastro** [comment]
@rozgo @dnaicker Hey guys, We changed our architecture a lot after the version in those tutorials. It is done to make it compatible with Parachain XCMP and easy connection to other Parachain. We are not using generic asset anymore. We will be updating the tutorials in 1-2 months after our testnet v3 release.
