### ISSUE TITLE
Implement all left functions in CustomAssets

### ISSUE THREAD

**Issue by Gauthamastro** [Polkadex-Substrate/Polkadex#95]
**Describe the bug**

CustomAssets panic when createToken is called in a local network configuration. It happens because withdraw() is not implemented

**Comment by ksr30** [comment]
**Functions to be implemented :-** 
- [ ] withdraw
- [ ] get_permission
- [ ] decrease_balance_swap
- [ ] increase_balance_swap
- [ ] transfer_decrease0_increase1
- [ ]
